### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by muhammadhasnain121** [ismail-programmer/HBA-Web-Development#1]
Ismail bhai assalamualaikum,
Bhai aik masla ara ha, title sy hi,
Wo change hi nai hora
4,5 martaba try kia lkn ni hua,
Please help me
03256868389
mughalzadahasnain1@gmail.com

**Comment by ismail-programmer** [comment]
Apna save kya tha code? Ctrl or s ka button dubana sa save hoga,
Ya try kran wrna apna issue group ma post kr dan with code , so i can check

Group link:
https://www.facebook.com/groups/smashcode/?ref=share_group_link

**Comment by muhammadhasnain121** [comment]
Assalamualaikum Ismail bhai hogia title save,
Cntrl S kia phr reload kia or show hogia..
Thanks bhai
Love you ❤️🤗❤️😚💞

**Comment by ismail-programmer** [comment]
Resolved
